[package]
name = "nodara-core"
description = "Workflow execution engine, executor SDK, registry, policy and audit for Nodara-Core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
name = "nodara_core"
path = "src/lib.rs"

[dependencies]
nodara-schema = { path = "../nodara-schema" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions = "1.4"

[lints]
workspace = true
